### ISSUE TITLE
Qabel-Box

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-core#390]
Implement the Qabel-Box specification: https://github.com/Qabel/qabel.github.io/pull/101

* [ ] Create and list prefixes #391 https://github.com/Qabel/qabel-accounting/issues/23
* [ ] Generate device id
* [ ] Save device id locally #395 
* [ ] Internal backend for S3 upload/download/delete
* [ ] Create and update directory metadata files #394
* [ ] Volume creation
* [ ] Directory creation
* [ ] File Upload/Download
* [ ] Volume browsing
* [ ] File update
* [ ] File update conflict solution
* [ ] Folder update
* [ ] Folder sharing + drop messages
* [ ] Single File Sharing
* [ ] Unsharing

**Comment by audax** [comment]
https://github.com/Qabel/qabel-android/milestones/Box:%20Core%20Functions

https://github.com/Qabel/qabel-desktop/milestones/Box:%20Core%20Functions
